# Generated by Django 3.2.17 on 2023-03-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230310_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='event_time',
        ),
    ]
