# Generated by Django 3.2.17 on 2023-03-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_time_event_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='time',
        ),
    ]
