# Generated by Django 3.2.17 on 2023-03-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_event_time_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='event_time',
        ),
    ]
