# Generated by Django 3.2.17 on 2023-03-10 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_time_event_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='event_time_till',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 4, 28, 264304)),
        ),
    ]
