# Generated by Django 3.2.17 on 2023-03-10 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230310_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 13, 5, 11, 826684)),
        ),
    ]
