# Generated by Django 3.2.17 on 2023-03-15 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20230315_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 17, 2, 25, 649742)),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL),
        ),
    ]
