# Generated by Django 3.2.17 on 2023-03-20 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_event_event_time_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 16, 16, 7, 754414)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
